// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://doltpxwckdlcwsorgumr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRvbHRweHdja2RsY3dzb3JndW1yIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAxNjQ2MjgsImV4cCI6MjA2NTc0MDYyOH0.aePCtTvj8JMytTGWsyxus62DDE31BAMdPpziAnaeGgs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);